import "@/app/_styles/globals.css";
import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";
import { ResarvationProvider } from "./_components/ResarvaContext";
const josep = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: {
    template: "%s Wild Owasis",
    default: "WelCome to Wild Owasis",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josep.className} bg-primary-950 text-primary-50 min-h-screen flex flex-col`}
      >
        <Header />
        <div className="flex-1 px-6 py-12 grid">
          <main className="max-w-7xl mx-auto w-full">
            <ResarvationProvider>{children}</ResarvationProvider>
            {/* react components are already rendered on server */}
          </main>
        </div>
      </body>
    </html>
  );
}
